version: '3'

services:
  next:
    build: ./next
    volumes:
      - ./next:/app
      - /app/node_modules
    ports:
      - '80:3000'
    command: npm run dev

  debug:
    build: ./api/debug

  db:
    image: mongo:4.1.6-xenial


  prettier:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
