version: '3'

services:
  proxy:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - next
      - debug
    ports:
      - '80:80'

  next:
    build: ./next
    volumes:
      - ./next:/app
      - /app/node_modules
    command: npm run dev

  debug:
    build: ./api/debug
    volumes:
      - ./api/debug:/app
      - /app/node_modules
    environment:
      - DB_URL=mongodb://db:27017/debug
      # - DB_URL
    depends_on:
      - db
    command: npm run dev

  db:
    image: mongo:4.1.7-xenial
    environment:
      - DB_URL
    volumes:
      - .:/app
      - db:/data/db

  prettier:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run format

volumes:
  db:
